# Generated by Django 2.1.4 on 2018-12-28 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('todo_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'db_table': 'todos',
            },
        ),
        migrations.CreateModel(
            name='TodoStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todos')),
            ],
            options={
                'verbose_name': 'Todo Status History',
                'verbose_name_plural': 'Todo Status Histories',
                'db_table': 'todo_status_history',
            },
        ),
        migrations.CreateModel(
            name='TodoStatusTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('status_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Todo Status Type',
                'verbose_name_plural': 'Todo Status Types',
                'db_table': 'todo_status_types',
            },
        ),
        migrations.AddField(
            model_name='todostatushistory',
            name='todo_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TodoStatusTypes'),
        ),
        migrations.AddField(
            model_name='todos',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TodoStatusTypes'),
        ),
        migrations.AddField(
            model_name='todos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
